### ISSUE TITLE
NumberType not work in Annotation

### ISSUE THREAD

**Issue by mohamedyasser** [kunicmarko20/SonataAnnotationBundle#19]
i'm using last version this my code 

```
use KunicMarko\SonataAnnotationBundle\Annotation as Sonata;
use Symfony\Component\Form\Extension\Core\Type\NumberType;

@Sonata\FormField(
     *     type=NumberType::class
     * )
```

admin work fine but only this filed show as text

**Comment by kunicmarko20** [comment]
You need https://symfony.com/doc/current/reference/forms/types/integer.html if you want to show type number in html. Closing as this is not an issue with this bundle. Ping me to reopen if needed.

**Comment by mohamedyasser** [comment]
@kunicmarko20 variable is float not an integer

**Comment by kunicmarko20** [comment]
I tested with regular sonata admin without annotation and when using `Symfony\Component\Form\Extension\Core\Type\NumberType` the result was the same, so I think this is not connected to this bundle.
