### ISSUE TITLE
Migrations issue once Package installed

### ISSUE THREAD

**Issue by STPJ** [kunicmarko20/SonataAnnotationBundle#23]
As soon I am adding this package via Composer, all my migrations stop working in Symfony 4 and giving me errors on all of them.

bin/console make:migration
bin/console doctrine:migrations:diff

All migrations file created ARE in the src/Migrations folder, and are populated in the database.
But appear symfony just can'T find them anymore.

If I remove the package from my bundles.php, it work again without issues.
If I activate the package back, migrations issues come back.

I use Symfony 4.

**Comment by kunicmarko20** [comment]
Can you give me the stack trace of your exception? Maybe try specifying a path to your entities like explained [here](https://github.com/kunicmarko20/SonataAnnotationBundle#configuration).

```
sonata_annotation:
    directory: '%kernel.project_dir%/src/'
```

**Comment by kunicmarko20** [comment]
@STPJ was able to reproduce this, #24 should fix it, will make a new release now.

**Comment by kunicmarko20** [comment]
@STPJ just tagged new version https://github.com/kunicmarko20/SonataAnnotationBundle/releases/tag/1.1.2 update should resolve your issue
