### ISSUE TITLE
Annotations with Sonata Media Bundle

### ISSUE THREAD

**Issue by lordtyuk** [kunicmarko20/SonataAnnotationBundle#28]
|    Q        |   A
|------------ | -----
| Version     | 1.1

### Support Question

 I got a little bit stucked trying to use annotations with sonata media bundle. The following annotation gives me a headache and I couldn't find the problem 

```

/**
 * @Sonata\FormField(
 * type=\Sonata\AdminBundle\Form\Type\CollectionType::class, 
 * options={
 * "by_reference"=false, * "entry_type"=\Sonata\MediaBundle\Form\Type\MediaType::class, 
 * "entry_options"={ 
 * "label"=false, 
 * "context"="default", 
 * "provider"="http://sonata.media .provider.file" * }, 
 * "allow_add"=true, 
 * "required"=false, 
 * } 
 * )
 *
 * @ORM\ManyToMany(targetEntity="App\Application\Sonata\MediaBundle\Entity\Media", cascade={"persist"}, fetch="LAZY") 
 * @ORM\JoinTable(name="contractproperty_files")
 */ 

private $files;
```
The error received: 

> (1/1) FatalThrowableError Type error: Too few arguments to function Sonata\MediaBundle\Form\Type\MediaType::__construct(), 0 passed in C:\devs\majoros\collector\vendor\symfony\form\FormRegistry.php on line 92 and exactly 2 expected in MediaType.php line 48 at MediaType->__construct()in FormRegistry.php line 92 at FormRegistry->getType('\\Sonata\\MediaBundle\\Form\\Type\\MediaType')in FormFactory.php line 74 at FormFactory->createNamedBuilder('__name__', '\\Sonata\\MediaBundle\\Form\\Type\\MediaType', null, array('required' => false, 'label' => false, 'context' => 'default', 'provider' => 'http://sonata.media .provider.file', 'block_name' => 'entry'))in FormBuilder.php line 106 at FormBuilder->create('__name__', '\\Sonata\\MediaBundle\\Form\\Type\\MediaType', array('required' => false, 'label' => false, 'context' => 'default', 'provider' => 'http://sonata.media .provider.file', 'block_name' => 'entry'))in CollectionType.php line 39 

Do you have any idea? Current versions from composer.json: 
"php": "^7.1.3", 
"kunicmarko/sonata-annotation-bundle": "^1.1", 
"sonata-project/media-bundle": "^3.16",

**Comment by kunicmarko20** [comment]
Writing `"Sonata\AdminBundle\Form\Type\CollectionType"` instead of `\Sonata\AdminBundle\Form\Type\CollectionType::class` fixed it for me, same for media class.

**Comment by lordtyuk** [comment]
Thx a lot, it really did the trick!
