### ISSUE TITLE
Add ability to remove fields from when when create/edit

### ISSUE THREAD

**Issue by Xymanek** [kunicmarko20/SonataAnnotationBundle#5]
Sometimes a field can be only edited on create, not after. For example a `User#username`. I suggest adding two new properties to `@Sonata\FormField()` - `create` and `edit`, both are true by default

This will also allow to configure the field for create and edit differently in case anyone needs to

**Comment by kunicmarko20** [comment]
hm, if I add create and edit properties how would that allow to configure the field differently? options would still be the same the only thing changes is if the field would show or not.

**Comment by Xymanek** [comment]
Do not add the field if the current action is disabled. That way I can specify two `@Sonata\FormField()` annotations on a field - and only one of them will be used based on which action it is currently

**Comment by kunicmarko20** [comment]
Ah, so I need to allow multiple `@Sonata\FormField()` yes, that would work. Thank you for the idea.

**Comment by kunicmarko20** [comment]
Added in https://github.com/kunicmarko20/SonataAnnotationBundle/commit/d1a99d22c80d255c8f2567b212750ce08ce35ff2. Thank you @Xymanek!
