### ISSUE TITLE
Add documentation on how to extend the admin

### ISSUE THREAD

**Issue by Xymanek** [kunicmarko20/SonataAnnotationBundle#6]
This will be very useful in case a custom logic is required only in one of 2 methods of admin, and the rest can be configured using annotations

I also suggest renaming `KunicMarko\SonataAnnotationBundle\Admin\Admin` to `KunicMarko\SonataAnnotationBundle\Admin\AnnotationAdmin`

**Comment by kunicmarko20** [comment]
I agree. This will be added.

**Comment by kunicmarko20** [comment]
Added in https://github.com/kunicmarko20/SonataAnnotationBundle/commit/528aa1ba0808d602f370cf4dfff926a3f2e572a1.
