### ISSUE TITLE
AddRoute documentation typo?

### ISSUE THREAD

**Issue by Xymanek** [kunicmarko20/SonataAnnotationBundle#7]
```
 * @Sonata\AddRoute(name="import", path="/import")
 * @Sonata\AddRoute(name="send_mail", path="{id}/send_mail")
```

First begins with a slash, second doesn't. So what's the correct way?

**Comment by kunicmarko20** [comment]
I think that it should always work without the slash, will test it to be sure, also what do you think about allowing just:

```
 * @Sonata\AddRoute("import")
 * @Sonata\AddRoute(name="send_mail", path="{id}/send_mail")
```
and using `import` for name and path if path is not present?

**Comment by Xymanek** [comment]
It's ambiguous - is it global (`/import`) or per object (`/{id}/import`)?

Also would be nice to reduce the second line to just

```
 * @Sonata\AddRoute("send_mail", path="{id}/send_mail")
```

**Comment by kunicmarko20** [comment]
Well if it is per object you have to add `{id}`, will fix the docs and remove the `name=`.

**Comment by kunicmarko20** [comment]
It seems that it doesn't matter if you use `/` or no, fixed in https://github.com/kunicmarko20/SonataAnnotationBundle/commit/528aa1ba0808d602f370cf4dfff926a3f2e572a1. Thank you @Xymanek
